openapi: 3.1.3
info:
  title: Admin Card API
  version: 1.0.0

servers:
  - url: /{apiVersion}
    variables:
      apiVersion:
        default: v1

paths:
  /admin/cards:
    get:
      tags:
        - Admin
      summary: Get all cards (paged)
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            minimum: 0
        - name: size
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Paged cards
          content:
            application/json:
              schema:
                $ref: '../component-schemas/dto/dto-schemas.yaml#/components/schemas/CardAdminDto'
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/SecurityResponse'
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'

  /admin/cards/{cardId}:
    get:
      tags:
        - Admin
      summary: Get card by ID
      security:
        - bearerAuth: []
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Card
          content:
            application/json:
              schema:
                $ref: '../component-schemas/dto/dto-schemas.yaml#/components/schemas/CardAdminDto'
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/SecurityResponse'
        '404':
          description: Карты не существует
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'

    delete:
      tags:
        - Admin
      summary: Delete card
      security:
        - bearerAuth: []
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/SecurityResponse'
        '404':
          description: Карты не существует
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'

  /admin/cards/user/{userId}:
    get:
      tags:
        - Admin
      summary: Get all cards by user (paged)
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          required: true
          schema:
            type: integer
            minimum: 0
        - name: size
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Paged cards
          content:
            application/json:
              schema:
                $ref: '../component-schemas/dto/dto-schemas.yaml#/components/schemas/CardAdminDto'
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/SecurityResponse'
        '404':
          description: Пользователя не существует
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'

    post:
      tags:
        - Admin
      summary: Create card for user
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Created card
          content:
            application/json:
              schema:
                $ref: '../component-schemas/dto/dto-schemas.yaml#/components/schemas/CardAdminDto'
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/SecurityResponse'
        '404':
          description: Пользователя не существует
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'

  /admin/cards/{cardId}/activate:
    patch:
      tags:
        - Admin
      summary: Activate card
      security:
        - bearerAuth: []
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Activated card
          content:
            application/json:
              schema:
                $ref: '../component-schemas/dto/dto-schemas.yaml#/components/schemas/CardAdminDto'
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/SecurityResponse'
        '404':
          description: Карты не существует
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'

  /admin/cards/block-requests/{requestId}/block:
    patch:
      tags:
        - Admin
      summary: Block card by request
      security:
        - bearerAuth: []
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Blocked card
          content:
            application/json:
              schema:
                $ref: '../component-schemas/dto/dto-schemas.yaml#/components/schemas/CardAdminDto'
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/SecurityResponse'
        '404':
          description: Карты не существует
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'

  /admin/cards/block-requests/{requestId}:
    get:
      tags:
        - Admin
      summary: Get block request
      security:
        - bearerAuth: []
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Block request
          content:
            application/json:
              schema:
                $ref: '../component-schemas/dto/dto-schemas.yaml#/components/schemas/CardRequestDto'
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/SecurityResponse'
        '404':
          description: Заявки не существует
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'

  /admin/cards/block-requests:
    get:
      tags:
        - Admin
      summary: Get all block requests (paged)
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            minimum: 0
        - name: size
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Paged block requests
          content:
            application/json:
              schema:
                $ref: '../component-schemas/dto/dto-schemas.yaml#/components/schemas/CardRequestDto'
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/SecurityResponse'
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: '../component-schemas/web/response-shemas.yaml#/components/schemas/ExceptionResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT